config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts, only: %i[index show] do
    resources :comments
  end
  namespace :admin do
    resources :posts
    root to: 'posts#index'
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :posts

  validates :name, presence: :true
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_create_commit { broadcast_append_to 'comments' }
  belongs_to :post

  validates :content, :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend Enumerize

  CATEGORIES = %i[games development movies other].freeze

  belongs_to :author
  has_rich_text :content
  has_many :comments, dependent: :destroy

  enumerize :category, in: CATEGORIES, default: :other

  validates :content, :title, :description, :category, presence: true
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ApplicationController
    layout 'admin/application'
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    before_action :set_post, only: %i[edit update destroy]

    def index
      @posts = Post.eager_load(:author).all
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to admin_posts_path, success: 'Post created'
      else
        flash.now[:danger] = 'Oops, something went wrong!'
        render :new
      end
    end

    def edit; end

    def update
      if @post.update(post_params)
        redirect_to admin_posts_path, success: 'Post updated!'
      else
        flash.now[:danger] = 'Oops, something went wrong!'
        render :edit
      end
    end

    def destroy
      if @post.destroy
        flash[:success] = 'Post deleted!'
      else
        flash[:danger] = "Error while deleting post, please try again: #{@post.destroy}"
      end

      redirect_to admin_posts_path
    end

    private

    def post_params
      params.require(:post).permit(:title, :description, :category, :author_id, :content)
    end

    def set_post
      @post = Post.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :success
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = Comment.all
    @comment = @post.comments.build
  end

  def new
    @comment = @post.comments.build
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comments_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_comments_path(post_id: @comment.post_id), notice: "Tweet was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@comment, partial: 'comments/form', locals: { comment: @comment })  }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:name, :content, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show
  before_action :set_comments, only: :show

  def index
    @posts = Post.eager_load(:author).order(created_at: :desc).all.to_a
    @featured = @posts.shift
  end

  def show
    @comment = @post.comments.build
  end

  private


  def set_post
    @post = Post.eager_load(:author).find(params[:id])
  end

  def set_comments
    @comments = @post.comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/header_helper.rb
module HeaderHelper
  def blog_categories
    categories = Post::CATEGORIES.map do |category|
      "<a href='#' class='p-2 text-muted'>#{category}</a>"
    end

    categories
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/posts/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= f.input :title %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= f.input :description %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
   <%= f.input :category, collection: Post::CATEGORIES, include_blank: false %>
  </div>
  <div class="col-md-6">
    <%= f.association :author, prompt: "Select the author" %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
  </div>
</div>

<div class="row mt-5">
  <div class="col-md-12 text-center">
    <%= f.button :submit, class: 'btn btn-success btn-lg' %>
    <%= f.button :button, 'Clear', type: :reset, class: 'btn btn-warning btn-lg' %>
  </div>
</div>

app/views/admin/posts/edit.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <div class="row">
      <div class="col-md-6 text-left">
        <h2>Edit Post <%= @post.id %></h2>
      </div>
      <div class="col-md-6 text-right">
        <a href="<%= admin_posts_path %>"> <i class="fas fa-arrow-left"></i> back</a>
      </div>
    </div>
  </div>

</div>
<div class="row">
  <div class="col-md-8 mx-auto">
    <div class="card">
      <div class="card-body">
        <%= simple_form_for @post, url: admin_post_path do |f| %>
          <%= render partial: 'form', locals: { f: f, post: @post, authors: @authors } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="row">
  <div class="col-md-6">
    <p class="lead">Posts: <%= @posts.count %></p>
  </div>
  <div class="col-md-6">
    <a href="<%= new_admin_post_path %>" class="btn btn-info float-right">New Post</a>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Title</th>
          <th>Category</th>
          <th>Author</th>
          <th>Reactions</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
      <% if @posts.present? %>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.id %> </td>
            <td><%= post.title %></td>
            <td><%= post.category %></td>
            <td><%= post.author.name  %></td>
            <td>5</td>
            <td>
              <%= link_to 'Edit', edit_admin_post_path(post.id) %>
            </td>
            <td>
              <%= link_to 'Delete', admin_post_path(post.id), method: :delete %>
            </td>
          </tr>

        <% end %>
      <% else %>
        <tr>
          <td colspan="6" class="text-center"><span class="text-warning">0 posts found</span></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <div class="row">
      <div class="col-md-6 text-left">
        <h2>New Post</h2>
      </div>
      <div class="col-md-6 text-right">
        <a href="<%= admin_posts_path %>"> <i class="fas fa-arrow-left"></i> back</a>
      </div>
    </div>
  </div>

</div>
<div class="row">
  <div class="col-md-8 mx-auto">
    <div class="card">
      <div class="card-body">
        <%= simple_form_for @post, url: admin_posts_path do |f| %>
          <%= render partial: 'form', locals: { f: f, post: @post, authors: @authors } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <% if comment.id.present? %>
    <div class="row">
      <div class="col-md-12 border-bottom pb-2 mb-4">
        <p class="text-muted p-0"><%= comment.content %> </p>
        <p class="small"> By <strong><%= comment.name %></strong>, &nbsp;&nbsp;&nbsp; <%= comment.created_at.to_formatted_s(:short) %> </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Comment</h5>
        <%= simple_form_for comment, id: dom_id(comment), url:  post_comments_path(post_id: post.id) do |f| %>
          <%= f.input :post_id, as: :hidden %>
          <div class="row">
            <div class="col-md-12">
              <%= f.input :name, class: 'input-sm' %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <%= f.input :content %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.button :submit, 'Comment', class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<%= turbo_frame_tag "comment_form" do %>
  <%= render "comments/form", comment: @comment, post: @post %>
<% end %>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment, post: @post %>

app/views/comments/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <%= turbo_frame_tag dom_id(@comment) do %>
        <%= render @comment %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-dismissible alert-<%= type %>">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Rails Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">

    </div>
  </div>
</header>
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= blog_categories.join('').html_safe %>
  </nav>
</div>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light m-0">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= admin_root_path %>">Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="<%= root_path %>">Blog
            <span class="visually-hidden"></span>
          </a>
        </li>
    </div>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails blog - Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/litera/bootstrap.min.css" integrity="sha384-enpDwFISL6M3ZGZ50Tjo8m65q06uLVnyvkFO3rsoW0UC15ATBFz3QEhr3hmxpYsn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
  </head>

  <body>
    <%= render partial: 'layouts/admin/header' %>
    <div class="container mt-5">
      <%= render partial: 'layouts/flash' %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>

    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/litera/bootstrap.min.css" integrity="sha384-enpDwFISL6M3ZGZ50Tjo8m65q06uLVnyvkFO3rsoW0UC15ATBFz3QEhr3hmxpYsn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/header' %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      });
    </script>
  </body>
</html>

app/views/posts/_blog_post.html.erb
<div class="blog-post border-bottom pb-4 mb-4">
  <h2 class="blog-post-title"> <a href="<%= post_path(post) %>"> <%= post.title %> </a></h2>
  <p class="blog-post-meta"><%= post.description %> </p>
  <div class="row">
    <div class="col-md-2">
      <span data-toggle="tooltip" data-placement="top" title="Comments"><i class="fas fa-comment"></i> <small>(<%= post.comments.count%>)</small></span>
    </div>
    <div class="col-md-8 text-center"><%= time_ago_in_words post.created_at %> by <strong><%= post.author.name %></strong> </div>
    <div class="col-md-2 text-right pr-5"><small><span class="badge badge-<%= post.category %>"><%= post.category %> </span></small></div>
  </div>
</div><!-- /.blog-post -->

app/views/posts/index.html.erb
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic"><%= @featured.title %></h1>
    <p class="lead my-3"><%= @featured.description %> </p>
    <p class="lead mb-0"><a href="<%= post_path(@featured) %>" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

<div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">
        Read more
      </h3>

      <% @posts.each do |post| %>
        <%= render partial: 'posts/blog_post', locals: { post: post } %>
      <% end %>

      <nav class="blog-pagination">
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="#">Previous</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
      </nav>

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main><!-- /.container -->

app/views/posts/show.html.erb
<div class="blog-post border-bottom pb-4 mb-4">
  <p class="text-left"> <a href="<%= root_path %>"> <i class="fas fa-arrow-left"></i> Back</a></p>
  <h2 class="blog-post-title"> <%= @post.title %></h2>
  <p class="blog-post-meta"><%= @post.description %> </p>
  <p><%= @post.content %> </p>
  <div class="row">
    <div class="col-md-3">
      <span><i class="fas fa-heart text-danger" data-toggle="tooltip" data-placement="top" title="Like"></i> <small>(1)</small></span>
      <span><i class="fas fa-smile text-warning" data-toggle="tooltip" data-placement="top" title="Smile"></i> <small>(1)</small></span>
      <span><i class="fas fa-thumbs-up text-success" data-toggle="tooltip" data-placement="top" title="Thumbs Up"></i> <small>(1)</small></span>
    </div>
    <div class="col-md-7 text-center"><%= time_ago_in_words @post.created_at %> by <strong><%= @post.author.name %></strong> </div>
    <div class="col-md-2 text-right pr-5"><small><span class="badge badge-<%= @post.category %>"><%= @post.category %> </span></small></div>
  </div>
</div><!-- /.blog-post -->

<div id="comments">
  <div class="row mb-4">
    <div class="col-md-12 text-center mb-2">
      <h3>Do your comment</h3>
    </div>
    <div class="col-md-12">
      <%= turbo_frame_tag "comment_form" do %>
        <%= render "comments/form", comment: @comment, post: @post %>
      <% end %>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-md-12 text-center">
      <h3>Comments</h3>
    </div>
  </div>

  <%= turbo_stream_from 'comments' %>

  <div class="row">
    <div class="col-md-12">
      <%= turbo_frame_tag 'comments' do %>
        <%= render @comments %>
      <% end %>
    </div>
  </div>
</div>